export {default as MoleScene} from "./mole-scene.js"
export {default as LoseScene} from "./lose-scene.js"
export {default as MainScene} from "./main-scene.js"
export {default as MazeScene} from "./maze-scene.js"
export {default as TitleScene} from "./title-scene.js"
export {default as WinScene} from "./win-scene.js"
export {default as CheatScene} from "./cheat-scene.js"
